name: ai-hub
region: nyc
services:
  - name: api
    github:
      repo: ST0MP-EE5/ai-hub
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: DO_API_TOKEN
        scope: RUN_TIME
        type: SECRET
