# DigitalOcean App Platform Spec for MCP Server
name: mcp
region: nyc

# Custom domain for SSE streaming support
domains:
  - domain: mcp.m9m.dev
    type: PRIMARY

# Enable SSE streaming by disabling edge cache (requires custom domain)
disable_edge_cache: true

services:
  - name: mcp-server
    github:
      repo: ST0MP-EE5/mcp-server
      branch: main
      deploy_on_push: true
    source_dir: /
    dockerfile_path: /Dockerfile
    http_port: 3000
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: DO_API_TOKEN
        scope: RUN_AND_BUILD_TIME
        type: SECRET

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
